import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "./providers/QueryProvider";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { ModalContato } from "@/components/ModalContato";

export const metadata: Metadata = {
    title: "Sitelizar",
    description: "Generated by create next app",
};

const API =
    process.env.NEXT_PUBLIC_API_URL ||
    "http://sitelizar-backend.localhost:8080/wp-json";

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    let globalData = { data: { header: null, footer: null } };

    try {
        const response = await fetch(`${API}/global/header-footer`, {
            next: { revalidate: 60 },
        });

        if (response.ok) {
            const json = await response.json();

            globalData = json;
        }
    } catch (error) {
        console.error("Erro ao buscar header/footer:", error);
    }

    return (
        <html lang="pt-BR">
            <body>
                <QueryProvider>
                    <Header data={globalData.data.header} />
                    {children}
                    <Footer data={globalData.data.footer} />
                    <ModalContato />
                </QueryProvider>
            </body>
        </html>
    );
}
